### ISSUE TITLE
Error : not found

### ISSUE THREAD

**Issue by hectoruch** [devbridge/Styleguide#116] opened 2016-04-23 21:13 UTC
Hi!
I have this problem and I do not know why...

![untitled](https://cloud.githubusercontent.com/assets/8074563/14763994/0af9f062-09a8-11e6-891d-a034065256f9.png)

Thanks!

**Comment by 7immy** [comment] 2016-04-24 02:15
same here

**Comment by miezis** [comment] 2016-04-24 09:17
Duplicate of #109

**Closed by miezis** 2016-04-24 09:17 UTC
