### ISSUE TITLE
After running the server it shows Error: Not Found , 

### ISSUE THREAD

**Issue by mehedi-sharif** [devbridge/Styleguide#142] opened 2016-05-03 09:04 UTC
while running the " gulp start-styleguide" command it show an error like the image . 
<img width="1187" alt="screen shot 2016-05-03 at 3 01 52 pm" src="https://cloud.githubusercontent.com/assets/5304905/14978810/3d1823e4-1140-11e6-8340-b9f91101b26f.png">

**Comment by VaclovasV** [comment] 2016-05-03 09:40
duplicate of #109

**Closed by VaclovasV** 2016-05-03 09:40 UTC
