### ISSUE TITLE
Add ability to create category description

### ISSUE THREAD

**Issue by andrius1** [devbridge/Styleguide#96] opened 2016-02-23 15:26 UTC
I'll give real example: I have category for Buttons, and I'd like to write some basic rules, in this case - how to use buttons (for example, when &lt;a&gt; or &lt;button&gt; should be used). At the moment, the only solution is to add the same text lines to all snippets. 

I think text paragraph for general description at the top of category page would be good idea.

**Comment by VaclovasV** [comment] 2016-02-23 15:29
Duplicate of https://github.com/devbridge/Styleguide/issues/56

**Comment by gediminas-s** [comment] 2016-06-21 12:52
Closing due to duplicate

**Closed by gediminas-s** 2016-06-21 12:52 UTC
Labels: duplicate
